server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: simple-demo-mvc-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # First simple rout to the hello world service
            - id: hello-world-service
              uri: http://localhost:8088
              predicates:
                - Path=/api/hello-world/**
              filters:
#                - RewritePath=/api/(?<segment>.*), /${segment}
#                - RewritePath=/[^/]+/[^/]+(?<remaining>/.*), ${remaining}
#                - RewritePath=/[^/]+/hello-world(?<remaining>/.*), ${remaining}                -
                - RewritePath=/api/hello-world(?<remaining>/.*), ${remaining}
                - AddRequestHeader=X-Service-Region,EU
                - AddRequestHeader=X-Service-Timezone,CEST
